server:
  port: 8899
spring:
  application:
    name: Offer
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/AnasManagement?createDatabaseIfNotExist=true&jdbcCompliantTruncation=false
    hikari:
      username: root
      password:
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
  config:
    import: optional:configserver:http://localhost:8888
  mail:
    host: smtp.gmail.com
    port: 587
    username: anasmag15@gmail.com
    password: eyhndpckteehfquh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


